[providers]
python = "3.11"

[phases.setup]
nixPkgs = ["python311", "postgresql"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python -c 'from src.main import app; print(\"Build successful\")'"]

[start]
cmd = "gunicorn --workers 4 --bind 0.0.0.0:$PORT src.main:app"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"