[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "postgresql"]

[phases.install]
cmds = ["python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["python -c 'from src.main import app; print(\"Build successful\")'"]

[start]
cmd = "gunicorn --workers 4 --bind 0.0.0.0:$PORT src.main:app"