[build]
builder = "nixpacks"

[deploy]
startCommand = "python -m gunicorn --workers 4 --bind 0.0.0.0:$PORT src.main:app"
healthcheckPath = "/api/auth/login"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 